// filelist.f
+incdir+src/common
+incdir+src/protocols
+incdir+src/protocols/l2
+incdir+src/protocols/l3
+incdir+src/protocols/l4
+incdir+src/protocols/tunnel
+incdir+src/protocols/rdma
+incdir+src/protocols/storage
+incdir+src/protocols/app
+incdir+src/core
+incdir+src/parser

src/common/packet_defines.sv
src/common/packet_utils.sv
src/protocols/protocol_base.sv
src/protocols/l2/eth_header.sv
src/protocols/l2/vlan_header.sv
src/protocols/l2/mpls_header.sv
src/protocols/l3/ipv4_header.sv
src/protocols/l3/ipv6_header.sv
src/protocols/l3/arp_header.sv
src/protocols/l3/ipv6_ext_header.sv
src/protocols/l4/tcp_header.sv
src/protocols/l4/udp_header.sv
src/protocols/l4/icmp_header.sv
src/protocols/l4/icmpv6_header.sv
src/protocols/l4/sctp_header.sv
src/protocols/tunnel/vxlan_header.sv
src/protocols/tunnel/gre_header.sv
src/protocols/tunnel/geneve_header.sv
src/protocols/tunnel/erspan_header.sv
src/protocols/tunnel/gtp_header.sv
src/protocols/tunnel/ip_in_ip_header.sv
src/protocols/tunnel/vxlan_gpe_header.sv
src/protocols/tunnel/esp_header.sv
src/protocols/rdma/rocev2_header.sv
src/protocols/rdma/iwarp_header.sv
src/protocols/storage/nvme_tcp_header.sv
src/protocols/storage/iscsi_header.sv
src/protocols/app/ptp_header.sv
src/core/protocol_graph.sv
src/core/template_registry.sv
src/core/packet.sv
src/parser/protocol_parser.sv
src/parser/packet_comparator.sv
