/*
 * pkt_help.c — Standalone CLI help tool for net_packet SV library
 *
 * Compile:  gcc -o pkt_help pkt_help.c
 * Usage:    ./pkt_help [topic]
 *
 * Topics:   packet, error, options, ipv4, tcp, gre, gtp, geneve,
 *           vxlan, rocev2, fragment, segment, all
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* ======================================================================== */
static void help_packet(void)
{
    printf(
    "============================================================================\n"
    " Net Packet Generator — Usage Guide\n"
    "============================================================================\n"
    "\n"
    " 1. BASIC USAGE (single randomize call):\n"
    "    packet pkt = new();\n"
    "    pkt.randomize() with {\n"
    "        pkt_kind == ETH_IPV4_TCP;\n"
    "        outer_ipv4.src_addr == 32'hC0A80001;\n"
    "        tcp.dst_port == 16'd80;\n"
    "        pkt_len inside {[64:1518]};\n"
    "    };\n"
    "\n"
    " 2. TUNNEL PACKET:\n"
    "    pkt.randomize() with {\n"
    "        pkt_kind == ETH_IPV4_UDP_VXLAN_ETH_IPV4_TCP;\n"
    "        outer_ipv4.src_addr == 32'hC0A80001;\n"
    "        vxlan.vni == 24'd1000;\n"
    "        inner_ipv4.src_addr == 32'h0A000001;\n"
    "        tcp.dst_port == 16'd80;\n"
    "    };\n"
    "\n"
    " 3. VLAN CONTROL (no template needed):\n"
    "    pkt.randomize() with {\n"
    "        pkt_kind == ETH_IPV4_TCP;\n"
    "        outer_vlan_num == 2;              // QinQ\n"
    "        outer_vlan[0].vlan_id == 100;     // S-VLAN\n"
    "        outer_vlan[1].vlan_id == 200;     // C-VLAN\n"
    "    };\n"
    "\n"
    " 4. CATEGORY RANDOM (test all TCP packets):\n"
    "    pkt.randomize() with {\n"
    "        pkt_rand_kind == PKT_CAT_TCP;     // random from all TCP templates\n"
    "    };\n"
    "\n"
    " 5. RDMA (RoCEv2):\n"
    "    pkt.randomize() with {\n"
    "        pkt_kind == ETH_IPV4_UDP_ROCEV2;\n"
    "        rocev2.opcode       == RC_RDMA_WRITE_ONLY;\n"
    "        rocev2.dest_qp      == 24'h000100;\n"
    "        rocev2.reth_va      == 64'hDEAD_BEEF_0000_0000;\n"
    "        rocev2.reth_r_key   == 32'h1234;\n"
    "        rocev2.reth_dma_len == 32'd4096;\n"
    "    };\n"
    "    // Run: ./pkt_help rocev2  for full opcode table\n"
    "\n"
    " 6. ERROR/ABNORMAL PACKET:\n"
    "    Run: ./pkt_help error    for full error packet guide\n"
    "\n"
    "    Run: ./pkt_help options  for full options control guide\n"
    "\n"
    " 7. ACCESS FIELDS:\n"
    "    outer_eth / inner_eth         — Ethernet (outer/inner)\n"
    "    outer_ipv4 / inner_ipv4       — IPv4 (outer/inner)\n"
    "    outer_ipv6 / inner_ipv6       — IPv6 (outer/inner)\n"
    "    outer_udp / inner_udp         — UDP (outer/inner)\n"
    "    tcp, arp, icmp, sctp          — L4 (single instance)\n"
    "    vxlan, gre, geneve, gtp_u     — Tunnel headers\n"
    "    erspan_ii, erspan_iii, esp     — Tunnel/security\n"
    "    rocev2, iwarp                  — RDMA\n"
    "    nvme_tcp, iscsi                — Storage\n"
    "    outer_vlan[0..3]               — Outer VLAN tags\n"
    "    inner_vlan[0..3]               — Inner VLAN tags\n"
    "    outer_vlan_num / inner_vlan_num — VLAN tag count (0-4)\n"
    "    pkt_len                        — Total packet length\n"
    "\n"
    " 8. CATEGORIES (pkt_rand_kind):\n"
    "    PKT_CAT_ALL         — all templates\n"
    "    PKT_CAT_BASIC       — non-tunnel basic\n"
    "    PKT_CAT_TCP/UDP/ICMP/SCTP  — by L4 type\n"
    "    PKT_CAT_OUTER_IPV4/IPV6    — by outer L3\n"
    "    PKT_CAT_INNER_IPV4/IPV6    — by inner L3 (tunnel)\n"
    "    PKT_CAT_TUNNEL      — all tunnels\n"
    "    PKT_CAT_VXLAN/GRE/GENEVE/GTP/ERSPAN/NVGRE/VXLAN_GPE\n"
    "    PKT_CAT_ROCEV2/STORAGE/MPLS/MGMT/ESP\n"
    "\n"
    " 9. PARSED FIELD ACCESS (after unpack):\n"
    "    protocol_parser parser = new();\n"
    "    packet pkt = parser.parse(raw_bytes);\n"
    "    ipv4_header ip4 = pkt.get_ipv4(0);   // typed accessor\n"
    "    $display(\"src=%%s\", packet_utils::format_ipv4(ip4.src_addr));\n"
    "    tcp_header tcp = pkt.get_tcp(0);\n"
    "    $display(\"port=%%0d\", tcp.dst_port);\n"
    "\n"
    " 10. VALIDATION (protocol correctness check):\n"
    "    protocol_parser parser = new();\n"
    "    parser.verify_en = 1;   // enable checksum/field verification\n"
    "    parse_result_t r = parser.validate(pkt);\n"
    "    $display(\"%%s\", parser.result_to_string(r));\n"
    "\n"
    " 11. PCAP (capture file I/O):\n"
    "    Run: ./pkt_help pcap     for PCAP read/write guide\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_error(void)
{
    printf(
    "============================================================================\n"
    " Error/Abnormal Packet Construction Guide (set_chain)\n"
    "============================================================================\n"
    "\n"
    " set_chain(string) lets you construct ANY protocol combination,\n"
    " including invalid/abnormal ones not in the template library.\n"
    " Protocol graph validation is automatically bypassed (force_mode=1).\n"
    " All calc_fields still run — checksums, lengths, ethertypes auto-computed.\n"
    "\n"
    " Syntax: pkt.set_chain(\"TOKEN1_TOKEN2_TOKEN3_...\");\n"
    "         pkt.randomize() with { ... };\n"
    "         pkt.clear_chain();  // revert to normal template mode\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Category 1: Missing Layer (skip required protocol layer)\n"
    " -----------------------------------------------------------------------\n"
    "   pkt.set_chain(\"ETH_TCP\");              // skip IP\n"
    "   pkt.randomize() with { tcp.dst_port == 80; pkt_len == 64; };\n"
    "\n"
    "   pkt.set_chain(\"ETH_UDP\");              // skip IP\n"
    "   pkt.randomize() with { outer_udp.dst_port == 4789; pkt_len == 64; };\n"
    "\n"
    "   pkt.set_chain(\"ETH_VXLAN_ETH_IPV4_TCP\"); // skip outer IP+UDP\n"
    "   pkt.randomize() with { vxlan.vni == 100; pkt_len == 128; };\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Category 2: Duplicate Layer (same protocol appears multiple times)\n"
    " -----------------------------------------------------------------------\n"
    "   pkt.set_chain(\"ETH_ETH_IPV4_TCP\");     // double Ethernet\n"
    "   pkt.set_chain(\"ETH_IPV4_IPV4_TCP\");    // double IPv4\n"
    "   pkt.set_chain(\"ETH_IPV4_TCP_TCP\");     // double TCP\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Category 3: Wrong Layer Order (protocol at wrong position)\n"
    " -----------------------------------------------------------------------\n"
    "   pkt.set_chain(\"TCP_ETH_IPV4\");         // TCP before Ethernet\n"
    "   pkt.set_chain(\"ETH_GRE_IPV4_TCP\");     // GRE without outer IP\n"
    "   pkt.set_chain(\"ETH_IPV4_VXLAN_TCP\");   // VXLAN without UDP\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Category 4: Unsupported/Unusual Combinations\n"
    " -----------------------------------------------------------------------\n"
    "   pkt.set_chain(\"ETH_IPV4_UDP_VXLAN_ETH_IPV6_SCTP\");\n"
    "   pkt.set_chain(\"ETH_IPV6_GRE_IPV4_UDP_VXLAN_ETH_IPV4_TCP\");\n"
    "   pkt.set_chain(\"ETH_IPV4_ESP_IPV4_TCP\");\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Category 5: Abnormal Field Values (override soft constraints)\n"
    " -----------------------------------------------------------------------\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_TCP;\n"
    "       outer_ipv4.version == 5;         // invalid IP version\n"
    "       outer_ipv4.ihl == 3;             // IHL too small\n"
    "       outer_ipv4.ttl == 0;             // zero TTL\n"
    "       tcp.data_offset == 2;            // data_offset too small\n"
    "       pkt_len == 20;                   // shorter than headers\n"
    "   };\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Category 6: VLAN Abnormal\n"
    " -----------------------------------------------------------------------\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_TCP;\n"
    "       outer_vlan_num == 4;             // 4-layer VLAN stacking\n"
    "       outer_vlan[0].vlan_id == 0;      // reserved VLAN ID\n"
    "       outer_vlan[1].vlan_id == 4095;   // reserved VLAN ID\n"
    "   };\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Available Tokens for set_chain:\n"
    " -----------------------------------------------------------------------\n"
    "   L2:     ETH, MPLS\n"
    "   L3:     IPV4, IPV6, ARP\n"
    "   L4:     TCP, UDP, ICMP, ICMPV6, SCTP, IGMP\n"
    "   Tunnel: VXLAN, GRE, GENEVE, GTP_U, ERSPAN_II, ERSPAN_III,\n"
    "           VXLAN_GPE, ESP, IP_IN_IP\n"
    "   RDMA:   ROCEV2, IWARP\n"
    "   Store:  NVME_TCP, NVME_RDMA, ISCSI\n"
    "   App:    PTP, DNS, DHCP, DHCPV6, BFD\n"
    "   L2 Ctl: LLDP, LACP, STP, MAC_CONTROL, MACSEC, EAP\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_options(void)
{
    printf(
    "============================================================================\n"
    " Protocol Options Control Guide\n"
    "============================================================================\n"
    " All options use rand enable/value fields with soft defaults.\n"
    " Enable via randomize() with {}, no helper functions needed.\n"
    " Soft constraints allow override for error/abnormal testing.\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " TCP Options (tcp.opt_xxx)\n"
    " -----------------------------------------------------------------------\n"
    "   tcp.opt_mss_en       == 1;       // MSS (Kind=2, 4B)\n"
    "   tcp.opt_mss_val      == 16'd1460; // soft default: 1460\n"
    "\n"
    "   tcp.opt_wscale_en    == 1;       // Window Scale (Kind=3, 3B)\n"
    "   tcp.opt_wscale_val   == 8'd7;    // soft default: 0~14\n"
    "\n"
    "   tcp.opt_sack_perm_en == 1;       // SACK Permitted (Kind=4, 2B)\n"
    "\n"
    "   tcp.opt_ts_en        == 1;       // Timestamps (Kind=8, 10B)\n"
    "   tcp.opt_ts_val       == 32'h1234; // TSval\n"
    "   tcp.opt_ts_ecr       == 32'h0;    // TSecr\n"
    "\n"
    "   // SYN packet with full options:\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_TCP;\n"
    "       tcp.flags[1] == 1;  // SYN\n"
    "       tcp.opt_mss_en == 1; tcp.opt_wscale_en == 1;\n"
    "       tcp.opt_sack_perm_en == 1; tcp.opt_ts_en == 1;\n"
    "   };\n"
    "   // auto: options[] built, data_offset updated, padded to 4B\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " IPv4 Options (outer_ipv4.opt_xxx / inner_ipv4.opt_xxx)\n"
    " -----------------------------------------------------------------------\n"
    "   outer_ipv4.opt_rr_en     == 1;    // Record Route (Type=7)\n"
    "   outer_ipv4.opt_rr_slots  == 9;    // soft default: 1~9 slots\n"
    "\n"
    "   outer_ipv4.opt_ts_en     == 1;    // Timestamp (Type=68)\n"
    "   outer_ipv4.opt_ts_slots  == 4;    // soft default: 1~4 slots\n"
    "\n"
    "   outer_ipv4.opt_lsr_en    == 1;    // Loose Source Route (Type=131)\n"
    "   outer_ipv4.opt_lsr_count == 3;    // 1~4 addresses\n"
    "   outer_ipv4.opt_lsr_addrs[0] == 32'hC0A80001;\n"
    "   outer_ipv4.opt_lsr_addrs[1] == 32'hC0A80002;\n"
    "   outer_ipv4.opt_lsr_addrs[2] == 32'hC0A80003;\n"
    "   // auto: ihl updated, checksum recalculated\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " GRE Options (gre.xxx_flag)\n"
    " -----------------------------------------------------------------------\n"
    "   gre.c_flag == 1;                  // Checksum (auto-computed)\n"
    "   gre.k_flag == 1;                  // Key\n"
    "   gre.key    == 32'hDEAD_BEEF;\n"
    "   gre.s_flag == 1;                  // Sequence Number\n"
    "   gre.sequence_number == 32'd1;\n"
    "   // header: 4B(base) + 4B*flags = 4~16B\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Geneve TLV Options (geneve.opt_xxx)\n"
    " -----------------------------------------------------------------------\n"
    "   geneve.opt_en     == 1;           // Enable TLV generation\n"
    "   geneve.opt_num    == 2;           // 1~3 TLV options\n"
    "   geneve.opt_class0 == 16'h0100;    // Option 0: class\n"
    "   geneve.opt_type0  == 7'd1;        // Option 0: type\n"
    "   geneve.opt_data0  == 32'hAABBCCDD; // Option 0: 4B data\n"
    "   // auto: opt_len computed, each TLV = 8 bytes\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " GTP-U Extension Header (gtp_u.xxx)\n"
    " -----------------------------------------------------------------------\n"
    "   gtp_u.e_flag             == 1;    // Enable extension header\n"
    "   gtp_u.next_ext_hdr_type  == 8'h85; // PDU Session Container\n"
    "   // Common: 0x85=PDU Session, 0x84=NR RAN, 0x81=RAN Container\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " RoCEv2 Extended Headers (opcode driven)\n"
    " -----------------------------------------------------------------------\n"
    "   rocev2.opcode == RC_RDMA_WRITE_ONLY;    // auto: +RETH(16B)\n"
    "   rocev2.opcode == RC_RDMA_WRITE_ONLY_IMM; // auto: +RETH+ImmDt\n"
    "   rocev2.opcode == RC_CMP_SWAP;           // auto: +AtomicETH(28B)\n"
    "   rocev2.opcode == UD_SEND_ONLY;          // auto: +DETH(8B)\n"
    "   // Run: ./pkt_help rocev2  for full opcode table\n"
    "\n"
    " -----------------------------------------------------------------------\n"
    " Error Testing (override soft defaults)\n"
    " -----------------------------------------------------------------------\n"
    "   tcp.opt_mss_val     == 0;         // invalid MSS\n"
    "   tcp.opt_wscale_val  == 20;        // invalid scale > 14\n"
    "   outer_ipv4.opt_rr_slots == 0;     // invalid 0 slots\n"
    "   // All soft constraints — override freely, no conflict\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_ipv4(void)
{
    printf(
    "============================================================================\n"
    " IPv4 Options Construction Guide\n"
    "============================================================================\n"
    "\n"
    " Usage with randomize (recommended):\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_TCP;\n"
    "       outer_ipv4.opt_rr_en    == 1;    // enable Record Route\n"
    "       outer_ipv4.opt_rr_slots == 9;    // 9 address slots\n"
    "   };\n"
    "   // options auto-built, ihl auto-computed\n"
    "\n"
    "   pkt.randomize() with {\n"
    "       outer_ipv4.opt_ts_en    == 1;    // enable Timestamp\n"
    "       outer_ipv4.opt_ts_slots == 4;    // 4 timestamp slots\n"
    "   };\n"
    "\n"
    "   pkt.randomize() with {\n"
    "       outer_ipv4.opt_lsr_en    == 1;   // enable Loose Source Route\n"
    "       outer_ipv4.opt_lsr_count == 3;   // 3 route addresses\n"
    "   };\n"
    "\n"
    " Available static helpers (manual approach):\n"
    "   opt_nop()                               — NOP (Type=1, 1B)\n"
    "   opt_eol()                               — End (Type=0, 1B)\n"
    "   opt_record_route(num_slots)             — Record Route (Type=7)\n"
    "   opt_timestamp(num_slots, oflw_flag)     — Timestamp (Type=68)\n"
    "   opt_loose_source_route(addrs[$])        — LSR (Type=131)\n"
    "   opt_strict_source_route(addrs[$])       — SSR (Type=137)\n"
    "   build_options(raw_bytes)                 — Pad to 4-byte boundary\n"
    "\n"
    " Manual option building:\n"
    "   pkt.outer_ipv4.options = ipv4_header::opt_record_route(9);\n"
    "   pkt.do_pack();  // ihl auto-updates to account for options\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_tcp(void)
{
    printf(
    "============================================================================\n"
    " TCP Options Construction Guide\n"
    "============================================================================\n"
    "\n"
    " Usage with randomize (recommended):\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_TCP;\n"
    "       tcp.opt_mss_en      == 1;        // enable MSS\n"
    "       tcp.opt_mss_val     == 16'd1460; // MSS value\n"
    "       tcp.opt_wscale_en   == 1;        // enable Window Scale\n"
    "       tcp.opt_wscale_val  == 8'd7;     // shift count\n"
    "       tcp.opt_ts_en       == 1;        // enable Timestamps\n"
    "       tcp.opt_ts_val      == 32'h1234; // TSval\n"
    "       tcp.opt_sack_perm_en == 1;       // enable SACK Permitted\n"
    "   };\n"
    "   // options auto-built, data_offset auto-computed\n"
    "\n"
    " Error testing (override soft defaults):\n"
    "   pkt.randomize() with {\n"
    "       tcp.opt_mss_en  == 1;\n"
    "       tcp.opt_mss_val == 0;  // invalid MSS=0\n"
    "       tcp.opt_wscale_en  == 1;\n"
    "       tcp.opt_wscale_val == 20; // invalid scale > 14\n"
    "   };\n"
    "\n"
    " Available static helpers (manual approach):\n"
    "   opt_mss(1460)                          — MSS (Kind=2, 4B)\n"
    "   opt_window_scale(7)                    — Window Scale (Kind=3, 3B)\n"
    "   opt_sack_permitted()                   — SACK Permitted (Kind=4, 2B)\n"
    "   opt_timestamps(ts_val, ts_ecr)         — Timestamps (Kind=8, 10B)\n"
    "   opt_sack('{left, right, ...})          — SACK blocks (Kind=5, var)\n"
    "   opt_nop()                              — NOP padding (Kind=1, 1B)\n"
    "   opt_eol()                              — End of List (Kind=0, 1B)\n"
    "   build_options(raw_bytes)               — Pad to 4-byte boundary\n"
    "   opt_syn_default(mss, wscale, ts, tsr)  — Common SYN options combo\n"
    "\n"
    " Manual option building:\n"
    "   byte unsigned opts[$];\n"
    "   byte unsigned tmp[$];\n"
    "   tmp = tcp_header::opt_mss(1460);\n"
    "   foreach (tmp[i]) opts.push_back(tmp[i]);\n"
    "   tmp = tcp_header::opt_timestamps(32'h12345678, 0);\n"
    "   foreach (tmp[i]) opts.push_back(tmp[i]);\n"
    "   pkt.tcp.options = tcp_header::build_options(opts);\n"
    "   pkt.do_pack();\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_gre(void)
{
    printf(
    "============================================================================\n"
    " GRE Optional Fields Guide (RFC 2784/2890)\n"
    "============================================================================\n"
    "\n"
    " Optional fields (controlled by flags):\n"
    "   c_flag=1 -> Checksum(16b) + Reserved1(16b)  [+4 bytes]\n"
    "   k_flag=1 -> Key(32b)                        [+4 bytes]\n"
    "   s_flag=1 -> Sequence Number(32b)             [+4 bytes]\n"
    "\n"
    " Header size: 4 (base) + 4*(c_flag+k_flag+s_flag) = 4~16 bytes\n"
    "\n"
    " Usage:\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_GRE_IPV4_TCP;\n"
    "       gre.k_flag == 1;\n"
    "       gre.key    == 32'h0000_ABCD;\n"
    "       gre.s_flag == 1;\n"
    "       gre.sequence_number == 32'd1;\n"
    "   };\n"
    "\n"
    "   // With checksum (auto-computed in calc_fields):\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_GRE_IPV4_TCP;\n"
    "       gre.c_flag == 1;  // checksum auto-calculated\n"
    "       gre.k_flag == 1;\n"
    "       gre.key == 32'hDEAD_BEEF;\n"
    "   };\n"
    "\n"
    " NVGRE (Network Virtualization using GRE):\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_GRE_ETH_IPV4_TCP;  // GRE L2\n"
    "       gre.k_flag == 1;\n"
    "       gre.key == {24'h001234, 8'h00};  // VSID=0x1234, FlowID=0\n"
    "   };\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_gtp(void)
{
    printf(
    "============================================================================\n"
    " GTP-U Header Guide (3GPP TS 29.281)\n"
    "============================================================================\n"
    "\n"
    " Basic fields:\n"
    "   version(3b)=1, pt(1b)=1, message_type(8b)=0xFF(G-PDU)\n"
    "   teid(32b): Tunnel Endpoint Identifier\n"
    "   length(16b): auto-computed by calc_fields\n"
    "\n"
    " Optional fields (when e_flag|s_flag|pn_flag set):\n"
    "   sequence_number(16b), n_pdu_number(8b), next_ext_hdr_type(8b)\n"
    "   Header grows from 8B to 12B\n"
    "\n"
    " Usage:\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_UDP_GTP_U_IPV4_TCP;\n"
    "       gtp_u.teid == 32'h0000_ABCD;\n"
    "   };\n"
    "\n"
    "   // With sequence number:\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_UDP_GTP_U_IPV4_TCP;\n"
    "       gtp_u.teid   == 32'h0000_1234;\n"
    "       gtp_u.s_flag == 1;\n"
    "       gtp_u.sequence_number == 16'h0001;\n"
    "   };\n"
    "\n"
    " Common next_ext_hdr_type values:\n"
    "   0x00 = No more extension headers\n"
    "   0x03 = Long PDCP PDU Number\n"
    "   0x20 = Service Class Indicator\n"
    "   0x40 = UDP Port (for NR user plane)\n"
    "   0x81 = RAN Container\n"
    "   0x82 = Long PDCP PDU Number (old)\n"
    "   0x83 = Xw RAN Container\n"
    "   0x84 = NR RAN Container\n"
    "   0x85 = PDU Session Container\n"
    "   0xC0 = PDCP PDU Number\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_geneve(void)
{
    printf(
    "============================================================================\n"
    " Geneve TLV Options Guide (RFC 8926)\n"
    "============================================================================\n"
    "\n"
    " TLV format: Class(16b) | Type(8b) | R(3b)+Len(5b) | Data(Len*4 bytes)\n"
    "\n"
    " Usage with randomize (recommended):\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_UDP_GENEVE_ETH_IPV4_TCP;\n"
    "       geneve.opt_en     == 1;           // Enable TLV\n"
    "       geneve.opt_num    == 2;           // 2 TLV options\n"
    "       geneve.opt_class0 == 16'h0100;\n"
    "       geneve.opt_type0  == 7'd1;\n"
    "       geneve.opt_data0  == 32'hAABBCCDD;\n"
    "       geneve.opt_class1 == 16'h0100;\n"
    "       geneve.opt_type1  == 7'd2;\n"
    "       geneve.opt_data1  == 32'h11223344;\n"
    "   };\n"
    "\n"
    " Manual build:\n"
    "   byte unsigned opts[$], tlv[$];\n"
    "   byte unsigned data1[$] = '{8'hAA, 8'hBB, 8'hCC, 8'hDD};\n"
    "   tlv = geneve_header::build_tlv(16'h0100, 8'h01, data1);\n"
    "   foreach (tlv[i]) opts.push_back(tlv[i]);\n"
    "\n"
    "   pkt.geneve.options = geneve_header::build_options(opts);\n"
    "   pkt.geneve.opt_len = pkt.geneve.options.size() / 4;\n"
    "   pkt.do_pack();\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_vxlan(void)
{
    printf(
    "============================================================================\n"
    " VXLAN Header Guide (RFC 7348)\n"
    "============================================================================\n"
    "\n"
    " Fields:\n"
    "   flags(8b)    = 0x08 (I-flag set, auto-computed)\n"
    "   vni(24b)     = VXLAN Network Identifier\n"
    "   reserved(32b)= 0 (auto)\n"
    "   UDP dst_port = 4789 (auto-set by calc_fields)\n"
    "\n"
    " Usage:\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_UDP_VXLAN_ETH_IPV4_TCP;\n"
    "       vxlan.vni == 24'd1000;\n"
    "       outer_vlan_num == 1;\n"
    "       outer_vlan[0].vlan_id == 100;\n"
    "   };\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_rocev2(void)
{
    printf(
    "============================================================================\n"
    " RoCEv2 (IB Spec Ch9) — Opcode to Extended Header Mapping\n"
    "============================================================================\n"
    " Opcode                        | RETH | AETH | Atomic | AtoAck | DETH | Imm | IETH\n"
    " -------------------------------|------|------|--------|--------|------|-----|-----\n"
    " RC_SEND_ONLY           (0x04) |      |      |        |        |      |     |     \n"
    " RC_SEND_ONLY_IMM       (0x05) |      |      |        |        |      |  v  |     \n"
    " RC_SEND_ONLY_INV       (0x17) |      |      |        |        |      |     |  v  \n"
    " RC_RDMA_WRITE_ONLY     (0x0A) |  v   |      |        |        |      |     |     \n"
    " RC_RDMA_WRITE_ONLY_IMM (0x0B) |  v   |      |        |        |      |  v  |     \n"
    " RC_RDMA_WRITE_FIRST    (0x06) |  v   |      |        |        |      |     |     \n"
    " RC_RDMA_WRITE_MIDDLE   (0x07) |      |      |        |        |      |     |     \n"
    " RC_RDMA_WRITE_LAST     (0x08) |      |      |        |        |      |     |     \n"
    " RC_RDMA_WRITE_LAST_IMM (0x09) |      |      |        |        |      |  v  |     \n"
    " RC_RDMA_READ_REQ       (0x0C) |  v   |      |        |        |      |     |     \n"
    " RC_RDMA_READ_RESP_ONLY (0x10) |      |  v   |        |        |      |     |     \n"
    " RC_ACK                 (0x11) |      |  v   |        |        |      |     |     \n"
    " RC_CMP_SWAP            (0x13) |      |      |   v    |        |      |     |     \n"
    " RC_FETCH_ADD           (0x14) |      |      |   v    |        |      |     |     \n"
    " RC_ATOMIC_ACK          (0x12) |      |  v   |        |   v    |      |     |     \n"
    " UD_SEND_ONLY           (0x64) |      |      |        |        |  v   |     |     \n"
    " UD_SEND_ONLY_IMM       (0x65) |      |      |        |        |  v   |  v  |     \n"
    " RC_CNP                 (0x81) |      |      |        |        |      |     |     \n"
    "----------------------------------------------------------------------------\n"
    "\n"
    " Usage Examples:\n"
    "   // RDMA Write\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_UDP_ROCEV2;\n"
    "       rocev2.opcode       == RC_RDMA_WRITE_ONLY;\n"
    "       rocev2.dest_qp      == 24'h000100;\n"
    "       rocev2.reth_va      == 64'hDEAD_BEEF_0000_0000;\n"
    "       rocev2.reth_r_key   == 32'h0000_1234;\n"
    "       rocev2.reth_dma_len == 32'd4096;\n"
    "   };\n"
    "\n"
    "   // RDMA Read Request\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_UDP_ROCEV2;\n"
    "       rocev2.opcode       == RC_RDMA_READ_REQ;\n"
    "       rocev2.reth_va      == 64'h0000_0000_1000_0000;\n"
    "       rocev2.reth_r_key   == 32'h0000_5678;\n"
    "       rocev2.reth_dma_len == 32'd2048;\n"
    "   };\n"
    "\n"
    "   // Atomic Compare & Swap\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_UDP_ROCEV2;\n"
    "       rocev2.opcode          == RC_CMP_SWAP;\n"
    "       rocev2.atomic_va       == 64'h0000_0000_4000_0000;\n"
    "       rocev2.atomic_r_key    == 32'h0000_AAAA;\n"
    "       rocev2.atomic_swap_add == 64'h2;\n"
    "       rocev2.atomic_compare  == 64'h1;\n"
    "   };\n"
    "\n"
    "   // UD Send\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_UDP_ROCEV2;\n"
    "       rocev2.opcode      == UD_SEND_ONLY;\n"
    "       rocev2.deth_q_key  == 32'h0000_1111;\n"
    "       rocev2.deth_src_qp == 24'h000600;\n"
    "   };\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_fragment(void)
{
    printf(
    "============================================================================\n"
    " IP Fragmentation Guide (ip_fragment)\n"
    "============================================================================\n"
    "\n"
    " RFC 791 Rules:\n"
    "   - fragment_offset is in 8-byte units\n"
    "   - Non-last fragment payload MUST be multiple of 8 bytes\n"
    "   - Last fragment payload does NOT need 8-byte alignment\n"
    "   - DF flag (flags[1]=1): fragmentation is forbidden\n"
    "   - MF flag (flags[0]=1): more fragments follow\n"
    "   - All fragments share the same 'identification' field\n"
    "\n"
    " MTU auto-adjustment:\n"
    "   - User MTU is auto-adjusted for 8-byte alignment\n"
    "   - Example: MTU=1500, IP_hdr=20 -> payload=(1500-20)/8*8=1480\n"
    "   - Example: MTU=1499, IP_hdr=20 -> payload=(1499-20)/8*8=1480 (adjusted)\n"
    "   - Minimum MTU = IP_hdr + 8 bytes\n"
    "\n"
    " Usage:\n"
    "   packet pkt = new();\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_TCP;\n"
    "       outer_ipv4.identification == 16'hABCD;\n"
    "       pkt_len == 4000;\n"
    "   };\n"
    "   packet frags[$];\n"
    "   int n = ip_fragment::fragment(pkt, 1500, frags);\n"
    "\n"
    " Reassemble:\n"
    "   packet result = ip_fragment::reassemble(frags);\n"
    "\n"
    " Control:\n"
    "   ip_fragment::verbose = 1;  // print summary (default)\n"
    "   ip_fragment::verbose = 0;  // silent mode\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_segment(void)
{
    printf(
    "============================================================================\n"
    " TCP Segmentation Guide (tcp_segment) — TSO\n"
    "============================================================================\n"
    "\n"
    " Segment a large TCP packet by MSS:\n"
    "   packet pkt = new();\n"
    "   pkt.randomize() with {\n"
    "       pkt_kind == ETH_IPV4_TCP;\n"
    "       tcp.seq_num == 32'h1000;\n"
    "       tcp.flags   == 9'h018;    // PSH+ACK\n"
    "       pkt_len == 5000;           // large payload\n"
    "   };\n"
    "   packet segs[$];\n"
    "   tcp_segment::segment(pkt, 1460, segs);\n"
    "   // segs[0]: seq=0x1000, len=1460, flags=ACK\n"
    "   // segs[1]: seq=0x15B4, len=1460, flags=ACK\n"
    "   // segs[2]: seq=0x1B68, len=1460, flags=ACK\n"
    "   // segs[3]: seq=0x211C, len=620,  flags=PSH+ACK (last)\n"
    "\n"
    " Reassemble segments:\n"
    "   packet reassembled = tcp_segment::reassemble(segs);\n"
    "\n"
    " Segment behavior:\n"
    "   - TCP.seq_num increments by segment payload size\n"
    "   - PSH flag only on last segment\n"
    "   - IPv4.total_length updated per segment\n"
    "   - IPv4.header_checksum recomputed per segment\n"
    "   - L2 headers cloned unchanged\n"
    "   - Works with tunnel packets (VXLAN/GRE inner TCP)\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_pcap(void)
{
    printf(
    "============================================================================\n"
    " PCAP File I/O Guide\n"
    "============================================================================\n"
    "\n"
    " WRITE (generate pcap file for Wireshark or replay tools):\n"
    "   pcap_writer pw = new();\n"
    "   pw.open(\"output.pcap\");\n"
    "\n"
    "   // Single packet with timestamp:\n"
    "   packet pkt = new();\n"
    "   pkt.randomize() with { pkt_kind == ETH_IPV4_TCP; pkt_len == 100; };\n"
    "   pw.write_packet(pkt, 1000, 500);  // sec=1000, usec=500\n"
    "\n"
    "   // Batch write:\n"
    "   packet pkts[$];\n"
    "   // ... build packets ...\n"
    "   pw.write_packets(pkts);  // timestamps auto-increment (0s,1s,2s...)\n"
    "   pw.close();\n"
    "\n"
    " READ (parse pcap file into packet objects):\n"
    "   pcap_reader pr = new();\n"
    "   pr.open(\"input.pcap\");  // auto-detects big/little endian\n"
    "\n"
    "   // Read all at once:\n"
    "   packet pkts[$];\n"
    "   pr.read_all(pkts);\n"
    "   pr.close();\n"
    "\n"
    "   // Or read one-by-one:\n"
    "   pr.open(\"input.pcap\");\n"
    "   while (!pr.eof()) begin\n"
    "       packet pkt = pr.read_next();\n"
    "       if (pkt != null)\n"
    "           $display(\"%%s\", pkt.to_brief());\n"
    "   end\n"
    "   pr.close();\n"
    "\n"
    " ACCESS PARSED FIELDS:\n"
    "   packet pkt = pr.read_next();\n"
    "   ipv4_header ip4 = pkt.get_ipv4(0);\n"
    "   $display(\"src=%%s\", packet_utils::format_ipv4(ip4.src_addr));\n"
    "   tcp_header tcp = pkt.get_tcp(0);\n"
    "   $display(\"port=%%0d\", tcp.dst_port);\n"
    "\n"
    " VALIDATE AFTER READ:\n"
    "   protocol_parser parser = new();\n"
    "   parser.verify_en = 1;\n"
    "   parse_result_t r = parser.validate(pkt);\n"
    "   $display(\"%%s\", parser.result_to_string(r));\n"
    "\n"
    " FILE FORMAT:\n"
    "   Global header (24B): magic=0xA1B2C3D4, ver=2.4, link=Ethernet\n"
    "   Per-packet (16B header + data): ts_sec, ts_usec, incl_len, orig_len\n"
    "   Output file can be opened directly in Wireshark\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_validate(void)
{
    printf(
    "============================================================================\n"
    " Protocol Validation Guide (protocol_parser)\n"
    "============================================================================\n"
    "\n"
    " BASIC VALIDATION (protocol chain only):\n"
    "   protocol_parser parser = new();\n"
    "   parse_result_t result = parser.validate(pkt);\n"
    "   // Checks: non-empty, starts with ETH, valid transitions, header sizes\n"
    "\n"
    " FULL VERIFICATION (with verify_en=1):\n"
    "   parser.verify_en = 1;\n"
    "   parse_result_t result = parser.validate(pkt);\n"
    "   $display(\"%%s\", parser.result_to_string(result));\n"
    "\n"
    "   Checks include:\n"
    "   - IPv4: version==4, IHL consistency, checksum, total_length, TTL, flags\n"
    "   - IPv6: version==6, hop_limit, payload_length\n"
    "   - TCP:  data_offset, options alignment, reserved, flag combos, checksum\n"
    "   - UDP:  length >= 8, checksum (pseudo-header)\n"
    "   - ICMP/ICMPv6: type validity, checksum\n"
    "   - GRE:  version, checksum when c_flag=1\n"
    "   - VXLAN: I-bit set (RFC 7348), reserved fields\n"
    "   - Geneve: version, opt_len consistency\n"
    "   - GTP-U: version, pt, message_type\n"
    "   - ARP:  hw_type, proto_type, hw_len, proto_len, opcode\n"
    "   - ERSPAN: version fields\n"
    "   - Cross-layer: length consistency, type field vs actual next layer\n"
    "\n"
    " PARSE + VALIDATE:\n"
    "   packet parsed = parser.parse(raw_bytes);\n"
    "   parse_result_t r = parser.validate(parsed);\n"
    "\n"
    " OUTPUT FORMAT:\n"
    "   VALIDATE: PASS\n"
    "     Chain: PROTO_ETHERNET -> PROTO_IPV4 -> PROTO_TCP\n"
    "\n"
    "   VALIDATE: FAIL — 2 error(s)\n"
    "     Chain: PROTO_ETHERNET -> PROTO_IPV4 -> PROTO_TCP\n"
    "     ERROR: layer[1] IPv4: header_checksum=0xDEAD, expected 0x1234\n"
    "     ERROR: layer[2] TCP: checksum=0x0000, expected 0xABCD\n"
    "     WARNING: layer[1] IPv4: TTL=0 (packet will be dropped by routers)\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_topics(void)
{
    printf(
    "============================================================================\n"
    " pkt_help — Net Packet SV Library Quick Reference\n"
    "============================================================================\n"
    "\n"
    " Usage: pkt_help <topic>\n"
    "\n"
    " Available topics:\n"
    "   packet    — General usage (templates, VLAN, categories, field access)\n"
    "   error     — Error/abnormal packet construction (set_chain)\n"
    "   options   — Protocol options control (TCP/IPv4/GRE/Geneve/GTP-U/RoCEv2)\n"
    "   ipv4      — IPv4 options (Record Route, Timestamp, Source Route)\n"
    "   tcp       — TCP options (MSS, Window Scale, SACK, Timestamps)\n"
    "   gre       — GRE optional fields (checksum, key, sequence)\n"
    "   gtp       — GTP-U header and extension headers\n"
    "   geneve    — Geneve TLV options\n"
    "   vxlan     — VXLAN usage\n"
    "   rocev2    — RoCEv2 opcode table and extended headers\n"
    "   fragment  — IP fragmentation (ip_fragment)\n"
    "   segment   — TCP segmentation / TSO (tcp_segment)\n"
    "   pcap      — PCAP file read/write\n"
    "   validate  — Protocol field verification (verify_en)\n"
    "   all       — Print all topics\n"
    "\n"
    " Examples:\n"
    "   pkt_help packet       # how to build packets\n"
    "   pkt_help rocev2       # RoCEv2 opcode table\n"
    "   pkt_help options      # all protocol options\n"
    "   pkt_help all          # everything\n"
    "============================================================================\n"
    );
}

/* ======================================================================== */
static void help_all(void)
{
    help_packet();   printf("\n");
    help_error();    printf("\n");
    help_options();  printf("\n");
    help_ipv4();     printf("\n");
    help_tcp();      printf("\n");
    help_gre();      printf("\n");
    help_gtp();      printf("\n");
    help_geneve();   printf("\n");
    help_vxlan();    printf("\n");
    help_rocev2();   printf("\n");
    help_fragment(); printf("\n");
    help_segment();  printf("\n");
    help_pcap();     printf("\n");
    help_validate();
}

/* ======================================================================== */
int main(int argc, char *argv[])
{
    if (argc < 2) {
        help_topics();
        return 0;
    }

    const char *topic = argv[1];

    /* Support case-insensitive matching */
    if      (!strcasecmp(topic, "packet"))   help_packet();
    else if (!strcasecmp(topic, "error"))    help_error();
    else if (!strcasecmp(topic, "options"))  help_options();
    else if (!strcasecmp(topic, "ipv4"))     help_ipv4();
    else if (!strcasecmp(topic, "tcp"))      help_tcp();
    else if (!strcasecmp(topic, "gre"))      help_gre();
    else if (!strcasecmp(topic, "gtp"))      help_gtp();
    else if (!strcasecmp(topic, "geneve"))   help_geneve();
    else if (!strcasecmp(topic, "vxlan"))    help_vxlan();
    else if (!strcasecmp(topic, "rocev2"))   help_rocev2();
    else if (!strcasecmp(topic, "rdma"))     help_rocev2();
    else if (!strcasecmp(topic, "fragment")) help_fragment();
    else if (!strcasecmp(topic, "frag"))     help_fragment();
    else if (!strcasecmp(topic, "segment"))  help_segment();
    else if (!strcasecmp(topic, "tso"))      help_segment();
    else if (!strcasecmp(topic, "pcap"))     help_pcap();
    else if (!strcasecmp(topic, "validate")) help_validate();
    else if (!strcasecmp(topic, "verify"))   help_validate();
    else if (!strcasecmp(topic, "all"))      help_all();
    else if (!strcasecmp(topic, "help"))     help_topics();
    else {
        fprintf(stderr, "Unknown topic: %s\n\n", topic);
        help_topics();
        return 1;
    }

    return 0;
}
