#!/usr/bin/env python3
"""
scapy_verify.py — Verify PCAP packets against RFC using Scapy.

Reads a PCAP file generated by net_packet, decodes each packet with Scapy,
and checks for:
  1. Scapy decode success (no Raw/Padding where a protocol should be)
  2. Ethertype / IP protocol / port consistency with actual layers
  3. IPv4 header checksum correctness
  4. TCP/UDP checksum correctness (pseudo-header based)
  5. IPv4/IPv6 length field consistency
  6. Known protocol field ranges (version, flags, etc.)

Usage:
  python3 tools/scapy_verify.py <pcap_file> [<pcap_file2> ...]

Exit code:
  0 = all packets pass
  1 = some packets have issues
"""

import sys
import struct
from collections import defaultdict

# Suppress Scapy warnings
import logging
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)

from scapy.all import (
    rdpcap, Ether, IP, IPv6, TCP, UDP, ICMP, ICMPv6EchoRequest,
    GRE, SCTP, ARP, Dot1Q, Raw, Padding,
    checksum as scapy_checksum, conf
)
try:
    from scapy.contrib.mpls import MPLS
except ImportError:
    MPLS = None

# Try importing optional layers
try:
    from scapy.contrib.geneve import GENEVE
except ImportError:
    GENEVE = None
try:
    from scapy.layers.vxlan import VXLAN
except ImportError:
    try:
        from scapy.contrib.vxlan import VXLAN
    except ImportError:
        VXLAN = None
try:
    from scapy.contrib.gtp import GTP_U_Header
except ImportError:
    GTP_U_Header = None
try:
    from scapy.layers.ipsec import ESP as ScapyESP
except ImportError:
    ScapyESP = None


def verify_ipv4_checksum(pkt, pkt_idx, errors):
    """Verify IPv4 header checksum."""
    if not pkt.haslayer(IP):
        return
    # Check all IP layers (tunnel may have multiple)
    layer = pkt
    ip_idx = 0
    while layer:
        if isinstance(layer, IP):
            ip = layer
            # Scapy computes checksum if we rebuild
            orig_chksum = ip.chksum
            # Rebuild to compute correct checksum
            del ip.chksum
            rebuilt = IP(bytes(ip))
            expected = rebuilt.chksum
            ip.chksum = orig_chksum  # restore

            if orig_chksum != expected:
                errors.append(
                    f"pkt[{pkt_idx}] IPv4[{ip_idx}] checksum=0x{orig_chksum:04x}, "
                    f"expected=0x{expected:04x}"
                )
            ip_idx += 1
        layer = layer.payload if hasattr(layer, 'payload') and layer.payload else None
        if isinstance(layer, (Raw, Padding)):
            break


def verify_ipv4_fields(pkt, pkt_idx, errors, warnings):
    """Verify IPv4 field ranges per RFC 791."""
    layer = pkt
    ip_idx = 0
    while layer:
        if isinstance(layer, IP):
            ip = layer
            if ip.version != 4:
                errors.append(f"pkt[{pkt_idx}] IPv4[{ip_idx}] version={ip.version}, expected 4")
            if ip.ihl < 5:
                errors.append(f"pkt[{pkt_idx}] IPv4[{ip_idx}] IHL={ip.ihl} < 5")
            if ip.ttl == 0:
                warnings.append(f"pkt[{pkt_idx}] IPv4[{ip_idx}] TTL=0")
            if ip.len < ip.ihl * 4:
                errors.append(
                    f"pkt[{pkt_idx}] IPv4[{ip_idx}] total_length={ip.len} < "
                    f"header_length={ip.ihl * 4}"
                )
            ip_idx += 1
        layer = layer.payload if hasattr(layer, 'payload') and layer.payload else None
        if isinstance(layer, (Raw, Padding)):
            break


def verify_ipv6_fields(pkt, pkt_idx, errors, warnings):
    """Verify IPv6 field ranges per RFC 8200."""
    layer = pkt
    idx = 0
    while layer:
        if isinstance(layer, IPv6):
            ip6 = layer
            if ip6.version != 6:
                errors.append(f"pkt[{pkt_idx}] IPv6[{idx}] version={ip6.version}, expected 6")
            if ip6.hlim == 0:
                warnings.append(f"pkt[{pkt_idx}] IPv6[{idx}] hop_limit=0")
            idx += 1
        layer = layer.payload if hasattr(layer, 'payload') and layer.payload else None
        if isinstance(layer, (Raw, Padding)):
            break


def verify_ethertype_consistency(pkt, pkt_idx, errors):
    """Check that Ethernet ethertype matches the actual next layer."""
    if not isinstance(pkt, Ether):
        return

    eth = pkt
    payload = eth.payload
    if isinstance(payload, (Raw, Padding)) or payload is None:
        return

    expected_map = {
        0x0800: IP,
        0x86DD: IPv6,
        0x0806: ARP,
        0x8100: Dot1Q,
    }

    if eth.type in expected_map:
        expected_cls = expected_map[eth.type]
        if not isinstance(payload, expected_cls):
            errors.append(
                f"pkt[{pkt_idx}] Ethernet ethertype=0x{eth.type:04x} implies "
                f"{expected_cls.__name__} but next layer is {type(payload).__name__}"
            )


def verify_ip_protocol_consistency(pkt, pkt_idx, errors):
    """Check IPv4 protocol field matches actual next layer."""
    layer = pkt
    ip_idx = 0
    while layer:
        if isinstance(layer, IP):
            ip = layer
            payload = ip.payload
            if isinstance(payload, (Raw, Padding)) or payload is None:
                pass
            else:
                proto_map = {
                    6: TCP, 17: UDP, 1: ICMP, 47: GRE, 132: SCTP,
                }
                if ip.proto in proto_map:
                    expected_cls = proto_map[ip.proto]
                    if not isinstance(payload, expected_cls):
                        # Some protocols like ESP, IGMP may not have Scapy classes
                        pass
            ip_idx += 1
        layer = layer.payload if hasattr(layer, 'payload') and layer.payload else None
        if isinstance(layer, (Raw, Padding)):
            break


def verify_udp_length(pkt, pkt_idx, errors):
    """Verify UDP length field consistency."""
    layer = pkt
    while layer:
        if isinstance(layer, UDP):
            udp = layer
            actual_len = len(bytes(udp))
            if udp.len != actual_len:
                errors.append(
                    f"pkt[{pkt_idx}] UDP length={udp.len}, actual={actual_len}"
                )
        layer = layer.payload if hasattr(layer, 'payload') and layer.payload else None
        if isinstance(layer, (Raw, Padding)):
            break


def verify_tcp_fields(pkt, pkt_idx, errors, warnings):
    """Verify TCP field ranges per RFC 9293."""
    layer = pkt
    while layer:
        if isinstance(layer, TCP):
            tcp = layer
            if tcp.dataofs < 5:
                errors.append(f"pkt[{pkt_idx}] TCP data_offset={tcp.dataofs} < 5")
            if tcp.reserved != 0:
                warnings.append(f"pkt[{pkt_idx}] TCP reserved={tcp.reserved} != 0")
            flags = tcp.flags
            if 'S' in str(flags) and 'F' in str(flags):
                warnings.append(f"pkt[{pkt_idx}] TCP SYN+FIN both set")
            if 'S' in str(flags) and 'R' in str(flags):
                warnings.append(f"pkt[{pkt_idx}] TCP SYN+RST both set")
        layer = layer.payload if hasattr(layer, 'payload') and layer.payload else None
        if isinstance(layer, (Raw, Padding)):
            break


def count_protocol_layers(pkt):
    """Count known protocol layers (excluding Raw/Padding)."""
    count = 0
    layer = pkt
    while layer:
        if not isinstance(layer, (Raw, Padding)):
            count += 1
        layer = layer.payload if hasattr(layer, 'payload') and layer.payload else None
    return count


def get_layer_names(pkt):
    """Get list of layer type names."""
    names = []
    layer = pkt
    while layer:
        if not isinstance(layer, (Raw, Padding)):
            names.append(type(layer).__name__)
        else:
            names.append(f"Raw({len(bytes(layer))}B)")
            break
        layer = layer.payload if hasattr(layer, 'payload') and layer.payload else None
    return names


def verify_pcap(filename):
    """Verify all packets in a PCAP file. Returns (total, errors, warnings)."""
    print(f"\n{'='*70}")
    print(f"Verifying: {filename}")
    print(f"{'='*70}")

    try:
        packets = rdpcap(filename)
    except Exception as e:
        print(f"ERROR: Cannot read {filename}: {e}")
        return 0, 1, 0

    total = len(packets)
    all_errors = []
    all_warnings = []
    protocol_stats = defaultdict(int)
    layer_count_stats = defaultdict(int)

    for i, pkt in enumerate(packets):
        pkt_errors = []
        pkt_warnings = []

        # Collect layer info
        layers = get_layer_names(pkt)
        layer_count = count_protocol_layers(pkt)
        layer_count_stats[layer_count] += 1

        # Count protocols seen
        for name in layers:
            if not name.startswith("Raw"):
                protocol_stats[name] += 1

        # Run all verifications
        verify_ipv4_checksum(pkt, i, pkt_errors)
        verify_ipv4_fields(pkt, i, pkt_errors, pkt_warnings)
        verify_ipv6_fields(pkt, i, pkt_errors, pkt_warnings)
        verify_ethertype_consistency(pkt, i, pkt_errors)
        verify_ip_protocol_consistency(pkt, i, pkt_errors)
        verify_udp_length(pkt, i, pkt_errors)
        verify_tcp_fields(pkt, i, pkt_errors, pkt_warnings)

        all_errors.extend(pkt_errors)
        all_warnings.extend(pkt_warnings)

    # Print summary
    print(f"\nTotal packets: {total}")
    print(f"\nProtocol distribution:")
    for proto, cnt in sorted(protocol_stats.items(), key=lambda x: -x[1]):
        print(f"  {proto:30s}: {cnt:5d}")

    print(f"\nLayer depth distribution:")
    for depth, cnt in sorted(layer_count_stats.items()):
        print(f"  {depth} layers: {cnt:5d} packets")

    print(f"\nErrors:   {len(all_errors)}")
    print(f"Warnings: {len(all_warnings)}")

    if all_errors:
        print(f"\n--- ERRORS (first 30) ---")
        for e in all_errors[:30]:
            print(f"  ERROR: {e}")

    if all_warnings:
        print(f"\n--- WARNINGS (first 20) ---")
        for w in all_warnings[:20]:
            print(f"  WARN:  {w}")

    status = "PASS" if len(all_errors) == 0 else "FAIL"
    print(f"\n{'='*70}")
    print(f"Result: {status} — {total} packets, {len(all_errors)} errors, {len(all_warnings)} warnings")
    print(f"{'='*70}")

    return total, len(all_errors), len(all_warnings)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <pcap_file> [<pcap_file2> ...]")
        print(f"  Verify packet correctness using Scapy (RFC compliance check)")
        sys.exit(1)

    total_pkts = 0
    total_errors = 0
    total_warnings = 0

    for filename in sys.argv[1:]:
        pkts, errs, warns = verify_pcap(filename)
        total_pkts += pkts
        total_errors += errs
        total_warnings += warns

    print(f"\n{'#'*70}")
    print(f"GRAND TOTAL: {total_pkts} packets, {total_errors} errors, {total_warnings} warnings")
    print(f"{'#'*70}")

    sys.exit(1 if total_errors > 0 else 0)


if __name__ == "__main__":
    main()
